services:
  - docker
    
before_install:
  - docker build -f ci-cd/Dockerfile -t discount-commerce:latest .
  - docker run --rm -v -t "${PWD}:/app" -w "/app" discount-commerce:latest dotnet test DomainTests
    
script:
  -  dotnet test DomainTests