services:
  - docker
    
before_install:
  - docker build -f ci-cd/Dockerfile -t discount-commerce:latest .
script:
  - docker run --rm -v "${PWD}:/app" -w "/app" discount-commerce:latest dotnet test DomainTests